### ISSUE TITLE
Fitting View not Pointable for Users - ERROR500

### ISSUE THREAD

**Issue by kaho88** [dysath/seat-fitting#60] opened 2020-08-23 08:16 UTC
Hi,

after Updating to the new SeAT Version we re-Installed the Fitting Plugin.
Superadmins can point the "Fitting" side without a Problem. Normal Members cant.... They always get a 500 Error.

Logs Show:
Request to fitting was denied. The permission required is global.superuser

Doctrine side work fine for all members.
![fit1](https://user-images.githubusercontent.com/24758285/90974257-b3222280-e529-11ea-8434-4bebc6fe206a.png)
![fit3](https://user-images.githubusercontent.com/24758285/90974258-b4534f80-e529-11ea-9677-4ba31dd5a2a4.png)
![fit2](https://user-images.githubusercontent.com/24758285/90974259-b4ebe600-e529-11ea-9f50-cab95c0c404d.png)

**Comment by bradleyshelley** [comment] 2020-08-24 10:31
I am having the same error.

**Comment by kaho88** [comment] 2020-08-24 12:21
Hey @Crypta-Eve 
Sorry... Not on the Slack Server at the moment. But here the Logs:

The "Solution to run migration" didnt work.


`Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'corporation_id' in 'field list' (SQL: select `corporation_id` from `character_infos` where `character_id` in (93361068, 96715891, 2112723126, 2112833017, 2115460998))
https://auth.braindead-zombies.org/fitting`


`Illuminate\Database\Connection::runQueryCallback
vendor/laravel/framework/src/Illuminate/Database/Connection.php:669


     * @throws \Illuminate\Database\QueryException

     */

    protected function runQueryCallback($query, $bindings, Closure $callback)

    {

        // To execute the statement, we'll simply call the callback, which will actually

        // run the SQL against the PDO connection. Then we can calculate the time it

        // took to execute and log the query SQL, bindings and time in our memory.

        try {

            $result = $callback($query, $bindings);

        }

 

        // If an exception occurs when attempting to run a query, we'll format the error

        // message to include the bindings with SQL, which will make this exception a

        // lot more helpful to the developer instead of just the database's errors.

        catch (Exception $e) {

            throw new QueryException(

                $query, $this->prepareBindings($bindings), $e

            );

        }

 

        return $result;

    }

 

    /**

     * Log a query in the connection's query log.

     *

     * @param  string  $query

     * @param  array  $bindings

     * @param  float|null  $time

     * @return void

     */

`

**Comment by Crypta-Eve** [comment] 2020-08-24 15:02
> The "Solution to run migration" didnt work.

That would be because you have partially run migrations. You are essentially trying to run the same migration twice which wont work. Can you explain what you have done up until reaching this point? Is this an update from seat3 to seat4 or a fresh seat4 install? Are you using docker or blade install?

**Comment by kaho88** [comment] 2020-08-24 16:22
We did an Update to V4 and used blade install :)

**Comment by bradleyshelley** [comment] 2020-08-24 16:23
I am running fresh install of seat4 on blade install.

**Comment by Crypta-Eve** [comment] 2020-08-25 01:22
@bradleyshelley just confmirming that you also see the error of 

```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'corporation_id' in 'field list' (SQL: select `corporation_id` from `character_infos` where `character_id` in (93361068, 96715891, 2112723126, 2112833017, 2115460998))```

**Comment by bradleyshelley** [comment] 2020-08-25 01:26
Exactly the error.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'corporation_id' in 'field list' (SQL: select `corporation_id` from `character_infos` where `character_id` in (90537376, 90657388))

**Comment by Crypta-Eve** [comment] 2020-08-25 01:29
Cheers, thanks for that. I am closing this issue as this is a duplicate of #59. Also this is fixed in a patch that is getting pushed later today

**Closed by Crypta-Eve** 2020-08-25 01:29 UTC
Labels: question
