### ISSUE TITLE
doctrine report broken

### ISSUE THREAD

**Issue by ysm1mh** [dysath/seat-fitting#45] opened 2020-01-20 13:52 UTC
hi. since your last update. with alliance reports.  the doctrine report is broken.

get a error 500.
with debug on in seat. i found the error leading to 

Trying to get property 'alliance_id' of non-object (View: /var/www/seat/vendor/denngarr/seat-fitting/src/resources/views/doctrinereport.blade.php)
--
in 00a8667f80781c0a1c019a6876c96691bff6711d.php line 17

full error report:
[error.txt](https://github.com/dysath/seat-fitting/files/4086464/error.txt)

**Comment by zino73** [comment] 2020-01-25 13:00
i have the same error

**Comment by zino73** [comment] 2020-01-25 22:35
ok i resolved the problem by deleting corporation with NULL as name 

Duplicate of #43

**Closed** 2020-08-14 00:45 UTC
Labels: duplicate
